### ISSUE TITLE
Have issue running spatial_clustering_cv as it requires Fortran

### ISSUE THREAD

**Issue by cthwe** [tidymodels/spatialsample#158] opened 2024-03-06 04:37 UTC
I'm having problem with running spatial_clustering_cv for my dataset. So my dataset contains ID, latitude and longitude in 4326 CRS system. I converted it to sf object using this code: 
 cluster <- sf::st_as_sf(extracted, coords=c("lon_4326", "lat_4326"), crs = 4326)

However, I obtained this error when I run spatial clustering cv:
df_cluster <- spatial_clustering_cv(cluster, v=5, cluster_function="kmeans")

Error in do_one(nmeth) :
  long vectors (argument 1) are not supported in .Fortran

Also, is there a way to extract list of ID for each cluster?

**Comment by mikemahoney218** [comment] 2024-03-06 13:46
Hi @cthwe ! Is there any chance you'd be able to provide a [reprex](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) for this issue? Unfortunately, given the information you've provided here, I don't have a way to reproduce this bug and start figuring out what's going on here.

My only guess is that this is a bug in `kmeans()` itself when given a large data set -- my napkin math suggests that if you've got more than 46,000ish rows in your data set, R wouldn't be able to hand the distance matrix for your data over to Fortran. If I'm right and this is a decent sized data set, you might need to use a different cluster function or a different CV method.

> Also, is there a way to extract list of ID for each cluster?
Not built-in, but check out the second code chunk here:
https://github.com/tidymodels/spatialsample/issues/157#issuecomment-1924660480

**Comment by cthwe** [comment] 2024-03-18 00:39
spatial_block_cv should work for my analysis. Thanks for the help.

**Comment by mikemahoney218** [comment] 2024-03-18 01:18
Alright, glad to hear it. I'm going to close this issue because I can't currently reproduce it (without just crashing R) and the actual bug appears to not be in spatialsample -- but if anyone reading this in the future has further questions (or fixes), please feel free to open an issue or PR!

**Closed by mikemahoney218** 2024-03-18 01:18 UTC
Labels: reprex
